spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3308/betterme?serverTimezone=Asia/Seoul
        username: qmfpsp
        password: 4655
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: create
            use-new-id-generate-mappings: false
        show-sql: true
        properties:
            hibernate.format_sql: true